#include <string>
#include <dpp/dpp.h>
#include "climax.h"
#include "../../cfg/config.h"

bool is_player_ready(const dpp::message_create_t& event) {
    if (event.msg.content.substr(prefix.length()) == "ready") return true;
    if (event.msg.content.substr(prefix.length()) == "Ready") return true;
    if (event.msg.content.substr(prefix.length()) == "READY") return true;
    return false;
}

Cipher caesar {
    "Caesar",
    "Lw ehjdq zlwk wkh vnlhv. Dw iluvw, wkhb iolfnhuhg olnh idxowb oljkwv, glpplqj hyhub ihz krxuv ehiruh uhwxuqlqj wr qrupdo. Qr rqh wkrxjkw pxfk ri lw; pdbeh d vrodu ioduh, pdbeh vrph dwprvskhulf lqwhuihuhqfh. Exw zkhq wkh vwduv glvdsshduhg dowrjhwkhu, wkh sdqlf vhw lq. Wkh zruog zdv soxqjhg lqwr d shupdqhqw wzloljkw. Wkh fursv glhg iluvw, xqdeoh wr skrwrvbqwkhvlch, ohdylqj flwlhv uholdqw rq gzlqgolqj vwrfnslohv. Srzhu julgv idlohg xqghu wkh vwudlq ri frqvwdqw ghpdqg. Lq wkh fkdrv, shrsoh vrxjkw uhixjh xqghujurxqg, lq exqnhuv dqg pdnhvkliw vkhowhuv, sudblqj iru oljkw wr uhwxuq. Exw qrwklqj fdph. Deryh jurxqg, wkh hduwk wxuqhg frog dqg eulwwoh. Wkh rfhdqv iurch dw wkhlu hgjhv, fuhhslqj lqzdug. Wkh flwlhv—rqfh wrzhulqj vbperov ri kxpdq dfklhyhphqw—fuxpeohg lqwr wkh gdun, olihohvv kxvnv. Wkh odvw frppxqlfdwlrq iurp wkh rxwvlgh zruog uhsruwhg pdvv hydfxdwlrqv wrzdug wkh htxdwru, exw wkh hiiruw zdv wrr odwh. Kxpdqlwb, rqfh pdvwhuv ri wkh sodqhw, kdg ilqdoob orvw frqwuro ri wkhlu prvw edvlf hohphqw: wkh vxq.",
    "It began with the skies. At first, they flickered like faulty lights, dimming every few hours before returning to normal. No one thought much of it; maybe a solar flare, maybe some atmospheric interference. But when the stars disappeared altogether, the panic set in. The world was plunged into a permanent twilight. The crops died first, unable to photosynthesize, leaving cities reliant on dwindling stockpiles. Power grids failed under the strain of constant demand. In the chaos, people sought refuge underground, in bunkers and makeshift shelters, praying for light to return. But nothing came. Above ground, the earth turned cold and brittle. The oceans froze at their edges, creeping inward. The cities—once towering symbols of human achievement—crumbled into the dark, lifeless husks. The last communication from the outside world reported mass evacuations toward the equator, but the effort was too late. Humanity, once masters of the planet, had finally lost control of their most basic element: the sun.",
    ""
};

Cipher rot13 {
    "ROT13",
    "Gurer jnf ab jneavat, ab tenaq bhgoernx. Vg fgnegrq va juvfcref. Crbcyr jbhyq tb gb fyrrc naq arire jnxr hc. Ab srire, ab fvtaf bs fgehttyr. Ragver gbjaf jbhyq snyy fvyrag bireavtug, gurve fgerrgf yvggrerq jvgu fgvyy obqvrf ylvat va gurve orqf be ng gurve qvaare gnoyrf. Gur srj fheivibef pbhyq svaq ab pnhfr. Ubfcvgnyf jrer birejuryzrq, gura rzcgvrq nf qbpgbef fhpphzorq yvxr rirelbar ryfr. N arj srne gbbx ubyq—gur greebe bs fyrrc. Crbcyr gevrq gb fgnl njnxr sbe qnlf, unyyhpvangvat sebz rkunhfgvba, gurve rlrf oybbqfubg naq jvyq. Riraghnyyl, rirelbar fyrrcf. Naq va gung fyhzore, gur jbeyq terj dhvrgre. Gur uvtujnlf orpnzr rzcgl irvaf fgergpuvat npebff n qrnq ynaqfpncr. Oveqf ab ybatre fnat, gur jvaq pneevrq ab fbhaq, naq gur bprnaf fgbccrq gurve eryragyrff penfuvat ntnvafg gur fuberf. Vg jnf nf vs gur Rnegu vgfrys unq ragrerq n qrrc, rgreany fyrrc, naq vg jbhyq arire njnxra ntnva.",
    "There was no warning, no grand outbreak. It started in whispers. People would go to sleep and never wake up. No fever, no signs of struggle. Entire towns would fall silent overnight, their streets littered with still bodies lying in their beds or at their dinner tables. The few survivors could find no cause. Hospitals were overwhelmed, then emptied as doctors succumbed like everyone else. A new fear took hold—the terror of sleep. People tried to stay awake for days, hallucinating from exhaustion, their eyes bloodshot and wild. Eventually, everyone sleeps. And in that slumber, the world grew quieter. The highways became empty veins stretching across a dead landscape. Birds no longer sang, the wind carried no sound, and the oceans stopped their relentless crashing against the shores. It was as if the Earth itself had entered a deep, eternal sleep, and it would never awaken again.",
    ""
};

Cipher atbash {
    "Atbash",
    "Gsv xlmxivgv qfmtovh gszg lmxv wvurmvw sfnzm kiltivhh gfimvw lm gsvri xivzglih. Hpbhxizkvih tilzmvw zmw hsrugvw zh gsvri ulfmwzgrlmh xifnyovw, yirwtvh hmzkkvw orpv yirggov ylmvh, zmw vmgriv mvrtsylfisllwh dviv hdzooldvw yb gsv tilfmw zh hrmpslovh lkvmvw drgslfg dzimrmt. Rg dzh zh ru gsv vzigs yvmvzgs dzh grivw lu yvzirmt gsv dvrtsg lu sfnzmrgb’h znyrgrlm. Gsv dvzogsb girvw gl vhxzkv gl gsvri uligrurvw nzmhrlmh, yfg vevm gslhv hgifxgfivh uvoo, xlmhfnvw yb ozmwhorwvh li yfirvw rm gsv ifyyov lu xloozkhrmt nlfmgzrmh. Xrgrvh lmxv gvvnrmt drgs oruv yvxznv hkizdormt xvnvgvirvh lu hglmv zmw hgvvo, zyzmwlmvw xzih zmw wvivorxg yfrowrmth mld nlmfnvmgh gl z ulitlggvm viz lu sfnzm wlnrmzmxv. Hfierelih hxzevmtvw gsilfts gsv divxpztv uli hfkkorvh, gsvri slkv wdrmwormt drgs vzxs kzhhrmt wzb. Gsvb dsrhkvivw lu z ufgfiv dsviv sfnzmh orevw rm yfiildh orpv izgh, srwrmt uiln gsv evib kozmvg gszg lmxv hfhgzrmvw gsvn.",
    "The concrete jungles that once defined human progress turned on their creators. Skyscrapers groaned and shifted as their foundations crumbled, bridges snapped like brittle bones, and entire neighbourhoods were swallowed by the ground as sinkholes opened without warning. It was as if the earth beneath was tired of bearing the weight of humanity’s ambition. The wealthy tried to escape to their fortified mansions, but even those structures fell, consumed by landslides or buried in the rubble of collapsing mountains. Cities once teeming with life became sprawling cemeteries of stone and steel, abandoned cars and derelict buildings now monuments to a forgotten era of human dominance. Survivors scavenged through the wreckage for supplies, their hope dwindling with each passing day. They whispered of a future where humans lived in burrows like rats, hiding from the very planet that once sustained them.",
    ""
};

Cipher rail_fence {
    "Rail fence",
    " undpoi ar ic.ss iast eet.adh’haaired.seavksP  aiisthofn,rieru andmoae  tSiceuthse va ldl  etr;e rtoeoep ttsa rda vtto hae.scooemabro kdnl  ehhd   intsnree,olhu tsj ne nolm he  ut ebtf trtu ntrdvrn y  f atensgtcmek tamlsn s p hr niec ih eetdtdplv nnt wgtrw oids  annvrcaBteswsign ao fmngnycds h ctssrld nsawaa pn,beedyergoae iem.Ttmaudod trtiemnlGvmnclsd eefh  hatmigruc ertosies itln.Btews se  unesu ff—aefi l-ehsntsyaiitbinagw vtitaa rldurilgWeh  udr eetgt autohsgfcaeagRdnewreuu, i.Bteh  e eaaDytry  u i eewe,swt salsCowte,dlsopre.olreoat ig oatii,gigo oradtogeysp  hu  y,an ut u nutolaee.int ab odrn twhpigu r  he wfdatloeh prr pewn enpaey ent lp sologfrel enneoe,seetuv uall gru r  ocpTeno  re ibc  n,oddgtih ,fn oovolniheyn theeienet h.het p hwsti tnesealf henwwae,slb r h erid tedpi ,ncnl ndoni  .tnd onhiiuvmesmted antytd  treeepis n.rsaapuo rissp rj eetenah—acleato  e g iotrg vvdst",
    "When the sun turned red, people thought it was just another sign of climate change. Red sunsets were beautiful, at first. But then the red never went away. Day after day, the sun’s light became weaker, its warmth less and less. Crops withered, and livestock perished. People tried to adapt, living in constant twilight, growing food indoors, and rationing every scrap. But the sun was dying, and no amount of human ingenuity could save them. Scientists scrambled to understand what was happening, but every day the red glow faded a little more. The temperature dropped; winter set in permanently. Governments collapsed as people fought for the last remaining resources, desperate to survive just a little longer. But there was no escape. The sun—once a source of life—became a faint, blood-red ghost in the sky, fading into oblivion along with everything that had ever lived under its light.",
    "K4O2"
};

Cipher vigenere {
    "Vigenere",
    "Tt yazh tirq kse okl owbh eej ophru gkrvd, mup tulg ndw utfbeehbk. Wlv caen jdg kkmtv ajd oootn, pzve kiy. Lh trekpd avrumkkmer ip tbxqyhh, jpeliaj wews kse oovo, qcrkxtnc rvysiv, eeo felylbx wlv lin wvwv r wsotc otrqqy. Drzxahs qlsu imidt, phrlf srhzps xlbdhvg eeo rktglbx zmksij hbxfj rj tznpapw. Dcdrkd tqrahr sumkela, tuhwi oirgeo cexasomer ap tuh gclkyeeot gritk. Xypn yazh hyh tvzphe. Fnwe epzdtarrg igrr tznpapw, zlqkj qihlrg kzwl r ehecx, viwistltent woi. Fmkteo brfodh kyzsp tbzbj rzvcneguw oj vyigiroev tchh, sft phrus ndw ezwdeeh hf js. Kse navq tfopfhez, eagzvvw ryd neyhbkoijd. Sdeywsiv fvnaie grasv ej eha bydqb vploga srdzvg impru cedqb dru nravvfs, tksbtnc ohw hyh prdt xrrdhyv sw ehksr lbjlhv. Eha wbuzu, rrtp taezlbx zmks lefr, estdqv l wwsghzrqh, swajkrwsu xrupr w tulqb, vywqoyaglbx oeppr kf oootn.",
    "It came from the sky like any other storm, but this was different. The rain was thick and black, like oil. It coated everything it touched, seeping into the soil, clogging rivers, and filling the air with a toxic stench. Animals died first, their bodies bloated and rotting within hours of contact. Plants turned brittle, their leaves crumbling at the slightest touch. Then came the people. Skin blistered upon contact, lungs filled with a thick, suffocating tar. Cities became ghost towns overnight as survivors fled, but there was nowhere to go. The rain followed, endless and relentless. Shelters became tombs as the black sludge sealed every crack and crevice, choking out the last breaths of those inside. The world, once teeming with life, became a wasteland, blanketed under a thick, suffocating layer of black.",
    "lawandorder"
};

Cipher enigma {
    "Enigma",
    "kfkyk csmjs xfpii ipgyu effdi cepog pcnpq uszfo zhomf huvnx rnues wdsnf lsimc eozgk chzdk yfnrj kwmeu zvtqu doytp zxzwd jvyzu ddcky rgrxy djjrb xwhme ngaac vtjzh qogec nojlr pgbdh rlzhk ezvrv baolh uujuh kqhkr weywc bswzq ojrtq jnyzy ahheo vzwxy xyfan cgztx nxqrg maaho uxscy slosf ogefp svunj rvyto sovub cuehf ddhtw zugqt mbywt ufunw isdob qioqx jjevm zqkds swfry pmovw ensmy gdgol xrlyv hhdow uvltu xnoep zlmui cjikm krodk mczzw evlmc pxgnk gmsvb qxuck xtkux kblwg kogkt gwihv mndma ctyhg izthh rxnkq jtdct zieag ibqjl winkl xnclz yrtlj vcunm vohxk onkqh qcntq tthtz wieji ocpcu vehca lyhrs kgffp yfpxm seytj illyc raxah ifavc qokoj vzlzy bhtbi dywtc wzltj fppjk xiqqo zgakb pstxf zytyd mvixn dgars npzrw uawms rfkzn xzglm uvbid qopay oiujp davcl tpleb dngul fodpt qunnn nalju clqvu zxxpz lvqyo odvyq hfbgt xmilv mohrq ykpzz yefcj sypsk mrqjr ciqmr zxzyo rruhr fppwa ktkrj tbowt jatey uv",
    "There was a time when the hum of machines filled the world: cars, planes, factories, all running like clockwork. But one by one, they fell silent. It started with the small things: phones stopped working, then cars refused to start. Planes fell from the sky as their engines cut out mid-flight. The power grids failed last, plunging cities into a cold, dark silence. People gathered in the streets, desperate for answers, but none came. Without machines, humanity was helpless. Governments tried to restore order, but with no communications and no way to transport resources, they quickly collapsed. People scavenged what they could from the dead machines, but food and water soon ran out. The machines had been the heartbeat of human civilisation, and without them, the world fell into chaos. The only sounds left were the echoes of dying technology, fading away as the last remnants of human achievement crumbled to dust.",
    "M3, 'III, 3C 9I', 'V, 4D 5E', 'VII, 8H 18R', 'fk th is cr ap'"
};